<option value="Bank Mandiri">Bank Mandiri</option>
        <option value="Bank Bukopin">Bank Bukopin</option>
        <option value="Bank Danamon">Bank Danamon</option>
        <option value="Bank Mega">Bank Mega</option>
        <option value="Bank CIMB Niaga">Bank CIMB Niaga</option>
        <option value="Bank Permata">Bank Permata</option>
        <option value="Bank Sinarmas">Bank Sinarmas</option>
        <option value="Bank QNB">Bank QNB</option>
        <option value="Bank Lippo">Bank Lippo</option>
        <option value="Bank UOB">Bank UOB</option>
        <option value="Panin Bank">Panin Bank</option>
        <option value="Citibank">Citibank</option>
        <option value="Bank ANZ">Bank ANZ</option>
        <option value="Bank Commonwealth">Bank Commonwealth</option>
        <option value="Bank Maybank">Bank Maybank</option>
        <option value="Bank Maspion">Bank Maspion</option>
        <option value="Bank J Trust">Bank J Trust</option>
        <option value="Bank QNB">Bank QNB</option>
        <option value="Bank KEB Hana">Bank KEB Hana</option>
        <option value="Bank Artha Graha">Bank Artha Graha</option>
        <option value="Bank OCBC NISP">Bank OCBC NISP</option>
        <option value="Bank MNC">Bank MNC</option>
        <option value="Bank DBS">Bank DBS</option>
        <option value="BCA">BCA</option>
        <option value="BNI">BNI</option>
        <option value="BRI">BRI</option>
        <option value="BTN">BTN</option>
        <option value="Bank DKI">Bank DKI</option>
        <option value="Bank BJB">Bank BJB</option>
        <option value="Bank BPD DIY">Bank BPD DIY</option>
        <option value="Bank Jateng">Bank Jateng</option>
        <option value="Bank Jatim">Bank Jatim</option>
        <option value="Bank BPD Bali">Bank BPD Bali</option>
        <option value="Bank Sumut">Bank Sumut</option>
        <option value="Bank Nagari">Bank Nagari</option>
        <option value="Bank Riau Kepri">Bank Riau Kepri</option>
        <option value="Bank Sumsel Babel">Bank Sumsel Babel</option>
        <option value="Bank Lampung">Bank Lampung</option>
        <option value="Bank Jambi">Bank Jambi</option>
        <option value="Bank Kalbar">Bank Kalbar</option>
        <option value="Bank Kalteng">Bank Kalteng</option>
        <option value="Bank Kalsel">Bank Kalsel</option>
        <option value="Bank Kaltim">Bank Kaltim</option>
        <option value="Bank Sulsel">Bank Sulsel</option>
        <option value="Bank Sultra">Bank Sultra</option>
        <option value="Bank BPD Sulteng">Bank BPD Sulteng</option>
        <option value="Bank Sulut">Bank Sulut</option>
        <option value="Bank NTB">Bank NTB</option>
        <option value="Bank NTT">Bank NTT</option>
        <option value="Bank Maluku">Bank Maluku</option>
        <option value="Bank Papua">Bank Papua</option>